services:
  llm:
    container_name: llm
    image: llm:debug
    environment:
      - OLLAMA_MODEL=qwen2.5:3b
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  agent:
    container_name: agent
    image: agent:debug
    build: ./microservices/agent
    ports:
      - "3000:3000"
    environment:
      - LLM_BASE_URL=http://llm:11434
      - OLLAMA_MODEL=qwen2.5:3b
    depends_on:
      - llm

  backend:
    container_name: backend
    image: backend:debug
    ports:
      - "4000:4000"

volumes:
  ollama_data:
